[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "caliper"
dynamic = ["version"]
description = 'web crawler for reporting website contents and urls'
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
keywords = []
authors = [
  { name = "Rebecca Sutton Koeser", email = "rebecca.s.koeser@princeton.edu" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "spider_rs",
  "tqdm"
]

[project.urls]
Documentation = "https://github.com/princeton-CDH/caliper#readme"
Issues = "https://github.com/princeton-CDH/caliper/issues"
Source = "https://github.com/princeton-CDH/caliper"

[project.scripts]
caliper = "caliper.crawl:main"

[project.optional-dependencies]
dev = ["pre-commit", "pytest", "pytest-cov"]

[tool.hatch.version]
path = "src/caliper/__init__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/caliper tests}"

[tool.pytest.ini_options]
addopts = "--cov=caliper --cov-report=term-missing --import-mode=importlib"

[tool.coverage.run]
source_pkgs = ["caliper"]
branch = true
parallel = true
omit = [
  "src/caliper/__about__.py",
]

[tool.coverage.paths]
caliper = ["src/caliper", "*/caliper/src/caliper"]
tests = ["tests", "*/caliper/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
