name: unit tests
on:
  push: # push to main & develop
    branches:
      - main
      - develop
  pull_request: # all PRs
concurrency:
  # Cancel existing job(s) for workflow when a new one is queued
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v6
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create python venv with uv
        run: uv venv
      - name: Install spider-rs via pip
        run: uv run pip install spider-rs==0.0.56
      - name: Install dependencies
        run: uv sync --extra dev --no-install-package spider-rs
      - name: Run tests
        run: uv run pytest --cov-report=xml --cov-report=term
      # Only upload test coverage for Python 3.12
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v5
        if: matrix.python == '3.12'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
